  language: python
  os:
    - linux
  cache: pip
  python:
    - 3.6
  install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - pip install -r requirements.txt
    - pip install --upgrade sip
    - pip install codecov
    - pip install -e .[test]
  script:
    - pytest
  after_script:
    - codecov