  language: python
  cache: pip
  python:
    - 3.6
  addons:
    apt:
      packages:
        - xvfb
  install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - pip install -r requirements.txt
    - pip install -e .[test]
    - sudo apt-get install python3-pyqt5  
  script:
    - pytest test