version: 1
formatters:
  default:
    class: cranio.utils.UTCFormatter
    format: '[%(asctime)s.%(msecs)03d] {%(filename)s:%(lineno)d} %(state)s %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: default
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: default
    filename: app.log
    maxBytes: 1000000
    backupCount: 3
loggers:
  cranio:
    level: DEBUG
    handlers: [console, file]
    propagate: False
root:
  level: DEBUG
  handlers: [console, file]