# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.5-stretch-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install --upgrade sip
            pip install codecov
            pip install -e .[test,lint]

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run black linter
          command: |
            . venv/bin/activate
            black --check .

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest --cov-report html:test-reports/cov_html --cov=cranio

      - run:
          name: run sqlite-to-csv.py
          command: |
            . venv/bin/activate
            sqlite-to-csv.py cranio.db

      - store_artifacts:
          path: test-reports
          destination: test-reports
